### ISSUE TITLE
Software that need registration

### ISSUE THREAD

**Issue by chrunchyjesus** [luongvo209/Awesome-Linux-Software#387]
What are your thoughts about software that need some kind of registration before download, for example [Davinci Resolve](https://www.blackmagicdesign.com/products/davinciresolve/)? Should they be included in the list?

I do not think @luongvo209 would want to make an account for every software he tries, so I think it is not practical. On the other hand, there are many of them that are truly *awesome linux software*.

**Comment by SaintFenix** [comment]
Hmmm, I'm thinking we could just use the non-free tag for davinci since it's registered for the free beta, but the "regular" version of it is a paid for bit of software.

But if that doesn't suffice, perhaps we could make a little tiny image that says registration and put it after it. Or perhaps just always mention the registration in the definition of the software.

**Comment by luongvo209** [comment]
@chrunchyjesus Hahaa lol you are half right and half wrong.  

> I do not think @luongvo209 would want to make an account for every software he tries  

Sure you are right. I do ALWAYS sign up for an account if it is necessary. When I don't, the reason is simple: the software requires money being paid. I don't have the budget for this and what I usually do in these situations is to look around: if that software is good, there are definitely someone using it, at least some reviews, a reddit thread.... anything. The fact that a software is not free doesn't prevent us all from listing it here ;)

**Comment by chrunchyjesus** [comment]
Understood, will add those I know of after my change gets merged.

**Comment by chrunchyjesus** [comment]
@luongvo209 Take your time, it is not like I am in a rush or anything. ;)
